stages:
  - build

build-package:
  image: $CI_REGISTRY_IMAGE:latest
  stage: build
  script:
    - apt-get install python3-venv
    - pip3 install build
    - python3 -m build
  artifacts:
    paths:
      - dist/*.whl