stages:
  - build

build-package:
  image: ubuntu:latest
  stage: build
  script:
    - apt-get update -q && apt-get install --no-install-recommends python3-pip curl unzip
    - curl --location --header "PRIVATE-TOKEN: glpat-S-UGaQrqRvSGpJbzHQYw" "https://gitlab.univ-nantes.fr/api/v4/projects/23117/jobs/artifacts/ci/download?job=build-package" --output gdal.zip
    - unzip gdal.zip
    - apt-get install -f ./gdal/dist/*.deb --no-install-recommends
    - pip3 install wheel setuptools numpy matplotlib scipy pyproj scikit-image pyhdf pyresample netcdf4 h5py requests pygrib cartopy
    - python3 .\setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl